#!/usr/bin/zsh
# Time-stamp: <2025-07-02 16:32:18 krylon>

export BORG_RELOCATED_REPO_ACCESS_IS_OK=yes
export BORG_REPO=wintermute:/data/Files/backup/borg/`hostname -s`
export BORG_PASSPHRASE="Wer das liest, ist doof."

ARCHIVE_NAME=`date +%Y_%m_%d`

echo "Backup to ${BORG_REPO}::${ARCHIVE_NAME}"

borg create --sparse \
     ::$ARCHIVE_NAME \
     ~/Dokumente \
     ~/diary/{diary,Apotheken}.org.xz \
     .zshrc \
     .config/{fish,mpv,dconf,gh,mate} \
     ~/go/src/github.com/blicero \
     /data/code/{python,scripts,dreamland} \
     ~/bin \
     ~/.emacs.d \
     ~/OneDrive/Dokumente \
     ~/.ssh \
     ~/.profile \
     ~/*.pub \
     ~/.thunderbird
