#!/usr/bin/zsh
# Time-stamp: <2025-03-07 19:25:34 krylon>

export BORG_REPO=wintermute:/data/Files/backup/borg/`hostname -s`
export BORG_PASSPHRASE="Wer das liest, ist doof."

borg prune --list -s -d 14 -w 6 -m 18
borg compact -p
